import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowRight, BrainCircuit, CheckCircle2, Gauge, RotateCcw, ShieldAlert, Sparkles } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
const fields = [
  ['Customer profile', [['gender','Gender',['Female','Male']],['senior_citizen','Senior citizen',['0','1']],['partner','Partner',['No','Yes']],['dependents','Dependents',['No','Yes']]]],
  ['Account details', [['tenure','Tenure (months)','number'],['contract','Contract',['Month-to-month','One year','Two year']],['paperless_billing','Paperless billing',['No','Yes']],['payment_method','Payment method',['Electronic check','Mailed check','Bank transfer (automatic)','Credit card (automatic)']]]],
  ['Services', [['phone_service','Phone service',['Yes','No']],['multiple_lines','Multiple lines',['No','Yes','No phone service']],['internet_service','Internet service',['DSL','Fiber optic','No']],['online_security','Online security',['Yes','No','No internet service']],['online_backup','Online backup',['Yes','No','No internet service']],['device_protection','Device protection',['Yes','No','No internet service']],['tech_support','Tech support',['Yes','No','No internet service']],['streaming_tv','Streaming TV',['Yes','No','No internet service']],['streaming_movies','Streaming movies',['Yes','No','No internet service']]]],
  ['Billing', [['monthly_charges','Monthly charges','number'],['total_charges','Total charges','number']]],
];
const initial = Object.fromEntries(fields.flatMap(([, group]) => group.map(([key,, options]) => [key, options === 'number' ? '' : options[0]])));

function App() {
  const [values, setValues] = useState<Record<string,string>>(initial); const [result, setResult] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(''); setResult(null); try { const payload = { ...values, senior_citizen: Number(values.senior_citizen), tenure: Number(values.tenure), monthly_charges: Number(values.monthly_charges), total_charges: Number(values.total_charges) }; const response = await fetch(`${API}/predict`, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(payload) }); if (!response.ok) throw new Error('Please complete the form with valid values.'); setResult(await response.json()); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to reach the prediction service.'); } finally { setLoading(false); } }
  const percent = result ? result.probability * 100 : 0;
  return <main><aside><div className="brand"><span><BrainCircuit size={21}/></span><b>Telco Churn<br/>AI</b></div><nav><a className="active"><Gauge size={18}/>Prediction</a><a><Activity size={18}/>Model insights</a><a><ShieldAlert size={18}/>About model</a></nav><div className="model-status"><i/>Model online<span>Logistic regression · 32 features</span></div></aside><section className="content"><header><div><p className="eyebrow">CUSTOMER INTELLIGENCE / LIVE MODEL</p><h1>Churn risk console</h1><p className="subhead">Turn customer signals into an actionable retention moment.</p></div><div className="header-pill"><Sparkles size={15}/> Session analytics</div></header><div className="workspace"><form onSubmit={submit}><div className="form-head"><div><h2>Customer profile</h2><p>Enter the account details to score.</p></div><span className="required">All fields required</span></div>{fields.map(([title, group]) => <fieldset key={title}><legend>{title}</legend><div className="field-grid">{group.map(([key,label,options]) => <label key={key}>{label}{options === 'number' ? <input required type="number" min="0" step={key.includes('charges') ? '0.01' : '1'} value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})}/> : <select required value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})}>{(options as string[]).map(option=><option key={option}>{option}</option>)}</select>}</label>)}</div></fieldset>)}{error && <p className="error">{error}</p>}<button className="submit" disabled={loading}>{loading ? 'Analyzing customer...' : <>Predict churn risk <ArrowRight size={18}/></>}</button></form><section className="result-panel">{result ? <><div className="result-top"><span className={`risk-dot ${result.risk_level.toLowerCase()}`}/><span>{result.risk_level} risk</span><button title="Reset result" onClick={()=>setResult(null)}><RotateCcw size={16}/></button></div><p className="result-label">CHURN PROBABILITY</p><div className="score">{percent.toFixed(1)}<small>%</small></div><div className="meter"><span style={{width:`${percent}%`}}/></div><h3>{result.prediction === 'Yes' ? 'Likely to churn' : 'Likely to stay'}</h3><p className="message">{result.message}</p><div className="insights"><h4>Model signals</h4>{result.contributions.map((item:any)=><div className="signal" key={item.feature}><span>{item.feature}</span><b className={item.impact >= 0 ? 'positive' : 'negative'}>{item.impact >= 0 ? '+' : ''}{item.impact}</b></div>)}</div><div className="recommendations"><h4>Suggested action</h4>{result.recommendations.map((item:string)=><p key={item}><CheckCircle2 size={15}/>{item}</p>)}</div></> : <div className="empty"><div className="empty-icon"><Gauge size={27}/></div><h2>Your score appears here</h2><p>Complete the profile and run the live model to see probability, signals, and next actions.</p></div>}</section></div></section></main>
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);